const handleError = (err) => {
  console.error(err)
  alert('Something went wrong, try again')
}

export {handleError}
